/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ppirraa (https://sketchfab.com/ghaisanids)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/floating-island-492f4a73ddb34d78b39fb4c9a00318c1
Title: Floating Island
*/

import { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three'

import escenaIsla from '../assets/3d/floating_island.glb';

const Isla = (props) => {
  const islaRef = useRef();
  const { nodes, materials } = useGLTF(escenaIsla);
  return (
    <a.group ref={islaRef} {...props}>
      <group scale={0.01}>
        <mesh      
          geometry={nodes.Cube_Material001_0.geometry}
          material={materials['Material.001']}
          position={[15.286, 167.734, -320.646]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[40.013, 3.519, 40.013]}
        />
        <mesh
          geometry={nodes.Cube001_Material_0.geometry}
          material={materials.Material}
          position={[12.381, 30.641, -276.976]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={234.686}
        />
        <mesh
          geometry={nodes.Cube002_Material002_0.geometry}
          material={materials['Material.002']}
          position={[15.286, 167.734, -234.262]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[40.013, 3.519, 40.013]}
        />
        <mesh
          geometry={nodes.Cube007_Material003_0.geometry}
          material={materials['Material.003']}
          position={[105.713, 110.397, -428.644]}
          rotation={[-Math.PI / 2, 0.107, -Math.PI / 2]}
          scale={26.184}
        />
        <mesh 
          geometry={nodes.Cube006_Material003_0.geometry}
          material={materials['Material.003']}
          position={[74.663, 110.397, -428.644]}
          rotation={[-Math.PI / 2, -0.107, Math.PI / 2]}
          scale={26.184}
        />
        <mesh 
          geometry={nodes.Cube005_Material003_0.geometry}
          material={materials['Material.003']}
          position={[-112.867, 110.397, -195.395]}
          rotation={[-Math.PI / 2, -0.107, Math.PI / 2]}
          scale={26.184}
        />
        <mesh
          geometry={nodes.Cone001_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-125.664, 171.103, -337.713]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh
          geometry={nodes.Cone009_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-79.824, 171.333, -330.963]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh
          geometry={nodes.Cone010_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-16.548, 171.333, -335.182]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh 
          geometry={nodes.Cone011_Material004_0.geometry}
          material={materials['Material.004']}
          position={[83.288, 171.333, -331.807]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh
          geometry={nodes.Cone012_Material004_0.geometry}
          material={materials['Material.004']}
          position={[90.319, 171.333, -385.803]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh
          geometry={nodes.Cone013_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-139.445, 171.333, -226.627]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh 
          geometry={nodes.Cone014_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-70.262, 171.333, -225.503]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh
          geometry={nodes.Cone015_Material004_0.geometry}
          material={materials['Material.004']}
          position={[-25.266, 171.333, -219.878]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
        <mesh
          geometry={nodes.Cone016_Material004_0.geometry}
          material={materials['Material.004']}
          position={[64.727, 171.333, -218.753]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[8.428, 8.428, 15.061]}
        />
      </group>
    </a.group>
  );
}

export default Isla;
